#cloud-config
write_files:
  - content: |
      - input:
        plugin: metrics_pull
        config:
          url: http://localhost:9090/metrics
          format:
            prometheus: {}
          poll_period: 15s
          namespace: catgpt
          retry_count: 0
          retry_delay: 1s
          timeout: 5s
          http_method: GET
        channel:
          channel_ref:
            name: cloud_monitoring
    path: /ua_config.d/catgpt_metrics.yaml
